// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBCjE0h1eHTYh0HgioXIIkUi5xQE9KcK0',
    appId: '1:26976369116:web:32b21c887b8ddb11337719',
    messagingSenderId: '26976369116',
    projectId: 'whatsappawesome-3c44e',
    authDomain: 'whatsappawesome-3c44e.firebaseapp.com',
    storageBucket: 'whatsappawesome-3c44e.appspot.com',
    measurementId: 'G-XQNSPC9Z57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQcbAk7XCaigd8ARgVbE9RY6GZCclwTKg',
    appId: '1:26976369116:android:f2bce919a37f6cba337719',
    messagingSenderId: '26976369116',
    projectId: 'whatsappawesome-3c44e',
    storageBucket: 'whatsappawesome-3c44e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMLJLHErhEtNTgeiz_gUv8r-rlDfvG4Qk',
    appId: '1:26976369116:ios:53cfab5a4c78d705337719',
    messagingSenderId: '26976369116',
    projectId: 'whatsappawesome-3c44e',
    storageBucket: 'whatsappawesome-3c44e.appspot.com',
    iosClientId: '26976369116-6fesv131bh1rqnpccn5ser24onfgqe2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappAwesome',
  );
}
